@startuml Internal elevator sequence
!pragma teoz true

title Watchdog utløper, sender ny kostforespørsel

participant Elevator
participant Distributor
participant Network
participant Watchdog

Distributor <- Watchdog: msg timer_expired(order)

@enduml
