@startuml Internal elevator sequence
!pragma teoz true

title Watchdog timer expired, initiates new cost request

participant Elevator
participant Distributor
participant Network
participant Watchdog

Distributor <- Watchdog: msg timer_expired()

@enduml
