@startuml modules

class Elevator {
  add_order(order)
  get_cost(order)
  set_lamp(order)
  clear_lamp(order)

  - msg_order_finished()
  - msg_new_order()
}

class Distributor

class Network {
  broadcast_cost_request()
  send_cost()
  broadcast_order()
  broadcast_order_finished()

  - msg_cost()
  - msg_order()
  - msg_order_acknowledge()
}

class Elev_hardware

class Watchdog {
  set_timer(order)
  clear_timer(order)

  - msg_timer_expired()
}

Watchdog <..> Distributor
Network <..> Distributor
Elevator <..> Distributor
Elevator <..> Elev_hardware

@enduml
