@startuml Network sequence
!pragma teoz true

title Network messages

participant HeisA as A
participant HeisB as B
participant HeisC as C





 -> A: Bestillingsknapp trykkes
 activate A

loop watchdog timeout

    A -> A: Spør alle heiser om\n kost for bestillingen
    A -> B
    activate B
    A -> C
    activate C

    A <-- A: Respons (kost)
    A <-- B
    A <-- C


    loop until response
    A -> A: Broadcast order
    A -> B
    A -> C

    A <-- B: Acknowledge order
    A <-- C


    <- A: Turn on light
    <- B
    <- C

    break Order finished
        B -> A: Broadcast order finished
        & B -> C
    <- A: Turn off light
    deactivate A
    <- B
        deactivate B
    <- C
        deactivate C

end
end


@enduml
