@startuml Internal elevator sequence
!pragma teoz true

title Receiving an order from another elevator

participant Elevator
participant Distributor
participant Network
participant Watchdog

Distributor <- Network: msg get_cost
Distributor -> Elevator: get_cost()
Distributor <-- Elevator: Response
Distributor -> Network: send_cost()

Distributor <- Network: msg order
Distributor -> Elevator: add_order()

Distributor -> Elevator: set_lamp()



@enduml
