@startuml Internal elevator sequence
!pragma teoz true

title Receives new order, another elevator has lowest cost

participant Elevator
participant Distributor
participant Network
participant Watchdog

Distributor <- Elevator: msg new_order
Distributor -> Elevator: get_cost()
Distributor -> Network: broadcast_cost_request()

Distributor <-- Elevator: Response
Distributor <-- Network: Response

Distributor -> Watchdog: set_timer()
Distributor -> Network: broadcast_order()
Distributor <-- Network: Response
Distributor -> Elevator: set_lamp()

Distributor <- Network: msg order_finished
Distributor -> Watchdog: clear_timer()

Distributor -> Elevator: clear_lamp()


@enduml
